### ISSUE TITLE
Standardize on a QR Code format?

### ISSUE THREAD

**Issue by psanford** [magic-wormhole/magic-wormhole-protocols#3]
Recently I've been working on adding QR Code support to the wormhole-william cli[1] and Android[2] apps. The idea is if you want to do a transfer from your computer to your phone, you can generate a QR code to scan instead of having to type the code into your phone.

I don't know if this is of interest to any other Magic Wormhole implementations. If it is, it would be nice to share a common url format embedded into the QR Code. I propose the following format:

```
wormhole:${relay_url}?code=${code}
```

So for example, using the default relay with a code of ` 1-babylon-locale` the embedded code would be:

```
wormhole:ws://relay.magic-wormhole.io:4000/v1?code=1-babylon-locale
```

If there is interest, I can open a PR to document this.

[1]: https://github.com/psanford/wormhole-william/pull/37
[2]: https://github.com/psanford/wormhole-william-mobile/pull/7

**Comment by piegamesde** [comment]
I'd been interested in this, yes.

**Comment by meejah** [comment]
Chiming in to note that gstreamer comes with realtime "recognize QR codes in video" plugins these days .. so it's easier than ever to automate collection of URLs from QR codes in video-streams.

With the above format, even a non-malicious QR-code scanner that simply visited every URL it saw would destroy the wormhole (since it seems common to have QR-codes that decode like `something:<url>` from the little I've seen).

I'm not sure what conclusion I'm trying to imply here, exactly .. but QR codes for transmitting security-critical secret things like this just make me "nervous" I guess. I suppose "it works for Signal Desktop pairing, so why not this" though :)

Maybe it would be slightly better if it was just the code (like `wormhole:1-babylon-locale`)? .... but also, *is* typing in the code a UX hurdle, given there's "tab-completion" (or I suppose that's called "autocomplete" on a phone ;) )

Anyway, all that aside, I think **if** implementations decide they want QR codes it would be best if there was a standard format so they inter-operated so :+1: for a PR...

**Comment by psanford** [comment]
> With the above format, even a non-malicious QR-code scanner that simply visited every URL it saw would destroy the wormhole (since it seems common to have QR-codes that decode like something:<url> from the little I've seen).

Nope. The URL `ws://relay.magic-wormhole.io:4000/v1?code=1-babylon-locale` is not "visitable" in a browser or by a crawler. You need to actually implement the rendezvous protocol + SPAKE to "destroy the wormhole".

**Comment by meejah** [comment]
Ahhh, right sorry it's been a while since I looked into the mailbox code. I'm still +1 on "if QR code, then having a standard is good" ..

**Comment by felinira** [comment]
The URI should probably encode the transfer type. As both sides can theoretically generate a code it could be nice to have a "send request" QR code as well.
